name: Testing Container
on:
    push:
        paths:
            - ".github/workflows/test.yml"
            - "requirements.txt"
            - "Dockerfile"
    pull_request:
        paths:
            - ".github/workflows/test.yml"
            - "requirements.txt"
            - "Dockerfile"

permissions:
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Extract version from requirements.txt
              id: get_version
              run: |
                  version=$(grep '^ansible-core==' requirements.txt | cut -d'=' -f3)
                  echo "version=$version" >> "$GITHUB_OUTPUT"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
              with:
                  images: |
                      ghcr.io/arillso/ansible
                      arillso/ansible
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=raw,value=${{ steps.get_version.outputs.version }}

            - name: Build and push
              uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
              with:
                  context: .
                  build-args: ANSIBLE_VERSION=${{ steps.get_version.outputs.version }}
                  push: false
                  load: true
                  tags: |
                      ${{ steps.meta.outputs.tags }}

            - name: Run Container Structure Tests
              run: |
                  docker run --rm \
                    -v "$GITHUB_WORKSPACE/tests/structure-test.yml:/structure-test.yaml" \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    gcr.io/gcp-runtimes/container-structure-test:latest \
                    test --image=arillso/ansible:${{ steps.get_version.outputs.version }} --config=/structure-test.yaml
