name: Testing Container
on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "requirements.txt"
      - "Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "requirements.txt"
      - "Dockerfile"

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "2.16.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/arillso/ansible
            arillso/ansible
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=${{ matrix.version }}-test

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: ANSIBLE_VERSION=${{ matrix.version }}
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
